name: npm trusted publishing

on:
  workflow_dispatch:

jobs:
  bootstrap:
    uses: zendesk/gw/.github/workflows/npm-trusted-publication.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_TOTP_DEVICE: ${{ secrets.NPM_TOTP_DEVICE }}
    with:
      package-name: '@zendesk/laika'
      package-json-file-path: package.json
      publish-workflow: ci-cd.yml
      repository: ${{ github.repository }}
      github-environment: npm-publish
