name: Publish Documentation

on:
  push:
    branches:
      - master
      - main

env:
  NODE_VERSION: 24

jobs:
  publish-docs:
    name: Publish documentation
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, zendesk-stable]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - id: find-yarn-cache-folder
        name: Find Yarn's cache folder
        run: echo "path=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"
      - name: Cache Yarn's cache folder
        uses: actions/cache@v5
        with:
          path: ${{ steps.find-yarn-cache-folder.outputs.path }}
          key: yarn-cache-folder-os-${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-folder-os-${{ runner.os }}-node-${{ env.NODE_VERSION }}-
            yarn-cache-folder-os-${{ runner.os }}-
      - id: find-yarn-cache-folder-docs
        name: Find Docs Yarn's cache folder
        run: |
          cd docs
          echo "path=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"
      - name: Cache Docs Yarn's cache folder
        uses: actions/cache@v5
        with:
          path: ${{ steps.find-yarn-cache-folder-docs.outputs.path }}
          key: yarn-cache-folder-docs-os-${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('docs/yarn.lock') }}
          restore-keys: |
            yarn-cache-folder-docs-os-${{ runner.os }}-node-${{ env.NODE_VERSION }}-
            yarn-cache-folder-docs-os-${{ runner.os }}-
      - name: Install dependencies
        run: |
          yarn install --immutable
          cd docs
          yarn install --immutable
      - name: Build and release docs
        run: |
          cd docs
          ./deploy.sh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
